### ISSUE TITLE
Get rid of ampersands on subroutine calls

### ISSUE THREAD

**Issue by davorg** [davorg/symbol-approx-sub#1]
I was young(er) and stupid. Lots of the subroutine calls in this module are of the form `&sub` where they should be `sub()`. This should be fixed.

**Comment by ankit01ojha** [comment]
I want to take this. Can you please tell me in which file are these errors

**Comment by davorg** [comment]
There are definitely a lot in the tests.
- https://github.com/davorg/symbol-approx-sub/tree/master/t

There's at least one in the documentation in the main library file.
- https://github.com/davorg/symbol-approx-sub/blob/master/lib/Symbol/Approx/Sub.pm

There may be some others in that file (but note that `goto &SUB` is correct).

It's worth checking the other library files too - but I don't think there are any there.

**Comment by ankit01ojha** [comment]
Sorry but I am unable to find any one other than the goto &sub which is correct as you said.

**Comment by davorg** [comment]
In https://github.com/davorg/symbol-approx-sub/blob/master/t/anon.t we have:

```
ok(&b eq 'aa');
```

That should be

```
ok(b() eq 'aa');
```

There are plenty more of those in the tests.

In the main library - https://github.com/davorg/symbol-approx-sub/blob/master/lib/Symbol/Approx/Sub.pm - on line 15 we have:

```
&aa; # executes &a if &aa doesn't exist.
```

It would be better if that was:

```
aa(); # executes a() if aa() doesn't exist.
```

It's entirely possible that there are no more occurrences in the libraries.

**Comment by ankit01ojha** [comment]
Thanks for the help, I working on it.

**Comment by davorg** [comment]
Done (mostly) in #7
