### ISSUE TITLE
Die with real Exceptions

### ISSUE THREAD

**Issue by davorg** [davorg/symbol-approx-sub#13]
We `croak()` in a few places - passing a string to `croak()`. It might be nicer to croak with real exception objects (something based on [Exception::Class](https://metacpan.org/pod/Exception::Class) perhaps).

**Comment by harikv** [comment]
I'll take this on.

**Comment by davorg** [comment]
Great. Thanks.

I'm just waiting for a Travis run to end before merging in a branch with some test changes. You might want to wait ten minutes before taking a branch.

**Comment by davorg** [comment]
All done. Go for it.

**Comment by davorg** [comment]
Done in #20
