### ISSUE TITLE
Remove svn artifacts

### ISSUE THREAD

**Issue by davorg** [davorg/symbol-approx-sub#3]
This module used to be stored in a subversion repository. There are still some svn artifacts in the code (e.g. `$Id$`).

Check all of the files and remove these.

**Comment by danielksan81** [comment]
Hi, i will remove them. Should the $Log$ also be removed?

**Comment by davorg** [comment]
Yes please. Nuke anything that looks like it came from svn.

Thanks.

**Comment by danielksan81** [comment]
Ok. In addition there is also stuff included like Revision 1.2  2005/10/22 17:56:22  dave in some files.
I think this also...?
