### ISSUE TITLE
Replace README.xml with README.md (or README.pod)

### ISSUE THREAD

**Issue by davorg** [davorg/symbol-approx-sub#4]
README.xml was always a stupid idea. What's better - Markdown or Pod?

**Comment by matthamil** [comment]
I'm on it :+1:

**Comment by davorg** [comment]
You may be too late, I'm afraid - https://github.com/gaurav1911/symbol-approx-sub :-/

**Comment by davorg** [comment]
Done in [PR#5](https://github.com/davorg/symbol-approx-sub/pull/5)
